runtime: python27
threadsafe: true
service: frontend
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /static
    static_dir: build/static
  - url: /manifest.json
    static_files: build/manifest.json
    upload: build/manifest.json
  - url: /asset-manifest.json
    static_files: build/asset-manifest.json
    upload: build/asset-manifest.json
  - url: /service-worker.js
    static_files: build/service-worker.js
    upload: build/service-worker.js
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
